# API Testing
GET http://localhost:8080/

###
# GET ALL NOTES
GET http://localhost:8080/api/v1/notes
Content-Type: application/json

###
# GET NOTE BY ID
GET http://localhost:8080/api/v1/notes/3
Content-Type: application/json

###
# CREATE NOTE
POST http://localhost:8080/api/v1/notes
Content-Type: application/json

{
  "judul": "Belajar Backend docker",
  "isi": "Gacor"
}

###
# UPDATE NOTE
PUT http://localhost:8080/api/v1/notes/8
Content-Type: application/json

{
  "judul": "Update Judul",
  "isi": "Update yok"
}

###
# DELETE NOTE
DELETE http://localhost:8080/api/v1/notes/8
Content-Type: application/json